### ISSUE TITLE
not really an issue: R sequence of scripts

### ISSUE THREAD

**Issue by steventsimpson** [skrypka/crowdflower-search#1]
Hi, your groups' scripts are awesome. 

I'm studying them to learn. I don't know Python yet, so I was wondering if you could tell me whether most of the same things are being done in R and Python?  It seems like maybe you each did a version of each task in whichever language your preferred and then combined your results. Is this right? 

Do you have a master file that notes the sequence in which these files should be run? 

Thanks!

**Comment by maherharb** [comment]
The python and R scripts are not redundant. Each person implemented certain modules of the solution using the language of their preference. The readme.md file details the sequence for running the scripts.

**Comment by steventsimpson** [comment]
Ah, so the sequence of the files directly map the master file process? 

Thanks!

~ Steve

Sent via telepathy
